version: '3.9'

services:
  wibutime-auth-postgres:
    image: postgres:16.2
    container_name: wibutime-auth-postgres
    restart: always
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - '9001:5432' #port pc -> docker
    environment:
      POSTGRES_DB: wibutime-auth
      POSTGRES_USER: wibutime-auth
      POSTGRES_PASSWORD: wibutime-auth
